services:
  # Backend service
  - type: web
    name: insurepredai-backend
    env: python
    buildCommand: ./build.sh
    startCommand: cd backend && gunicorn insurepred.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: insurepredai-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  # Frontend service
  - type: web
    name: insurepredai-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: https://insurepredai-backend.onrender.com

databases:
  - name: insurepredai-db
    plan: free
